image:
  name: antora/antora
publish:
  stage: deploy
  pages: true
  interruptible: true
  script:
    - echo $CI_PAGES_URL
    - antora --fetch --redirect-facility=static --to-dir=public --url $CI_PAGES_URL antora-playbook.yml
  artifacts:
    paths:
      - public
