site:
  title: Test Project
  start_page: package-a::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_paths:
        - a
        - b
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
